apiVersion: v1
kind: Namespace
metadata:
  name: pnegi13
  labels:
    app: poc
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pnegi-poc-cm
  namespace: pnegi13
  labels:
    app: poc
data
data:
  hostip: 10.198.23.4
  post: 8080
