apiVersion: v1
kind: Service
metadata:
  name: video-service
  namespace: pnegi13
spec:
  type: LoadBalancer
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp-video
  sessionAffinity: None
