apiVersion: v1
kind: Service
metadata:
  name: poc-service
spec:
  type: NodePort
  selector:
    app: poc
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30008
